DROP SEQUENCE PACIENTE_SEQ;

DROP SEQUENCE MEDICO_SEQ;

DROP SEQUENCE CONSULTA_SEQ;

DROP TABLE CONSULTA;

DROP TABLE PACIENTE;

DROP TABLE MEDICO;

CREATE SEQUENCE PACIENTE_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE MEDICO_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE CONSULTA_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE PACIENTE
(
	ID               INT          NOT NULL PRIMARY KEY,
	EMAIL            VARCHAR(100) NULL,
	SENHA            VARCHAR(15)  NOT NULL,
	NOME             VARCHAR(90)  NOT NULL,
	DATA_NASCIMENTO  DATE         NOT NULL,
	TELEFONE         DECIMAL(11)  NOT NULL,
	CPF              DECIMAL(11)  NOT NULL
);

CREATE TABLE MEDICO
(
	ID               INT          NOT NULL PRIMARY KEY,
	EMAIL            VARCHAR(100) NULL,
	SENHA            VARCHAR(15)  NOT NULL,
	NOME             VARCHAR(90)  NOT NULL,
	CRM              INT          NOT NULL,
	ESPECIALIDADE    VARCHAR(30)  NOT NULL
);

CREATE TABLE CONSULTA
(
	ID               INT          NOT NULL PRIMARY KEY,
	DATA_CONSULTA    TIMESTAMP    NOT NULL,
	VALOR            DECIMAL(8,2) NOT NULL,
	ENDERECO         VARCHAR(300) NOT NULL,
	ID_PACIENTE      INT          NOT NULL,
	ID_MEDICO        INT          NOT NULL,
	CONSTRAINT CONSULTA_PACIENTE_FK 
                FOREIGN KEY (ID_PACIENTE) 
                REFERENCES PACIENTE(ID),
    CONSTRAINT CONSULTA_MEDICO_FK 
                FOREIGN KEY (ID_MEDICO) 
                REFERENCES MEDICO(ID)                
);
	
	
	
	
	
	
	
	
	
	